1
Otus-DevOps-2022-05/Rezus2all_infra pull request #1
Opened 2022-07-11 19:57 UTC by Rezus2all

2022-07-12 11:56 UTC, mrgreyves requested changes
Здравствуйте!)
Это явно не похоже на выполненное дз
Рекомендую свериться с методичкой
ДЗ отправляю на доработку

2022-07-13 14:19 UTC, mrgreyves requested changes
Здравствуйте!
Все еще задания выполнены не корректно
Рекомендации от меня прежние
Если у вас есть какие то конкретные вопросы, вы можете оформить дополнительный пуллреквест =)

2022-07-14 18:36 UTC, Rezus2all commented
> Здравствуйте!) Это явно не похоже на выполненное дз Рекомендую свериться с методичкой ДЗ отправляю на доработку
Я понимаю, я на шаге где нужно со проверить в слак отображение коммита

2022-07-15 14:07 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все задания выполнены корректно
Не забудьте в следующих дз добавлять описание к вашим пуллреквестам
ДЗ принимаю =)

2022-07-15 15:32 UTC, Rezus2all commented
Здравствуйте.
Я еще раз прошу прощения – не совсем разбираюсь в интерфейсе Гита

С уважением,
Ахмет Шабакаев,
Старший специалист
отдела сопровождения прикладного программного обеспечения

***@***.***
г. Пенза, ул. Гагарина, 11а
+7 (963) 761 22 16
***@***.******@***.***>  www.rencredit.ru<http://www.rencredit.ru/>
[30_perfect_inst_circle]<https://www.instagram.com/rencreditpnz/>  [30_perfect_vk_circle] <https://vk.com/rencreditpenza>   [30_perfect_inplacers_circle] <https://inplacers.ru/renessans-kredit>

From: Vladimir Drozdetskiy ***@***.***>
Sent: Friday, July 15, 2022 5:08 PM
To: Otus-DevOps-2022-05/Rezus2all_infra ***@***.***>
Cc: Shabakaev, Akhmet ***@***.***>; Author ***@***.***>
Subject: Re: [Otus-DevOps-2022-05/Rezus2all_infra] 1 (PR #1)


@mrgreyves approved this pull request.

Здравствуйте!)
Вот теперь все задания выполнены корректно
Не забудьте в следующих дз добавлять описание к вашим пуллреквестам
ДЗ принимаю =)

—
Reply to this email directly, view it on GitHub<https://ddei5-0-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fOtus%2dDevOps%2d2022%2d05%2fRezus2all%5finfra%2fpull%2f1%23pullrequestreview%2d1040350107&umid=2B1035EE-E3D8-8C05-9227-57F3BD03D99F&auth=7fcf02acef238e77a8cb8229dc434ff7fae423d2-04f879a1a50c095c939026e684bb627c13f7b69c>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZ5JT4MABIZTUM7S7BCJHYDVUFWEDANCNFSM53IUUSHA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-07-21 13:23 UTC, merged

2022-10-11 07:42 UTC, Rezus2all commented
Я еще не сдавал 2 ДЗ по Гиту, у меня на питоне и установке хука остановилось

С уважением,
Ахмет Шабакаев,
Старший специалист
отдела сопровождения прикладного программного обеспечения

***@***.***
г. Пенза, ул. Гагарина, 11а
+7 (963) 761 22 16
***@***.******@***.***>  www.rencredit.ru<http://www.rencredit.ru/>
[30_perfect_inst_circle]<https://www.instagram.com/rencreditpnz/>  [30_perfect_vk_circle] <https://vk.com/rencreditpenza>   [30_perfect_inplacers_circle] <https://inplacers.ru/renessans-kredit>

From: Vladimir Drozdetskiy ***@***.***>
Sent: Tuesday, July 12, 2022 2:57 PM
To: Otus-DevOps-2022-05/Rezus2all_infra ***@***.***>
Cc: Shabakaev, Akhmet ***@***.***>; Author ***@***.***>
Subject: Re: [Otus-DevOps-2022-05/Rezus2all_infra] 1 (PR #1)


@mrgreyves requested changes on this pull request.

Здравствуйте!)
Это явно не похоже на выполненное дз
Рекомендую свериться с методичкой
ДЗ отправляю на доработку

—
Reply to this email directly, view it on GitHub<https://ddei5-0-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fOtus%2dDevOps%2d2022%2d05%2fRezus2all%5finfra%2fpull%2f1%23pullrequestreview%2d1035679783&umid=E3F494AE-E39A-5D05-9873-4FED63AA9EB9&auth=7fcf02acef238e77a8cb8229dc434ff7fae423d2-5b2c15d76360e8b02f3a64f4b5a18938cc28c6ab>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZ5JT4KZADZJP2JU4V6QWZLVTVMQVANCNFSM53IUUSHA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>