Cloud bastion
Otus-DevOps-2022-05/Rezus2all_infra pull request #2
Opened 2022-07-20 21:03 UTC by Rezus2all

выполнил ДЗ "Создаем VPN-сервер для серверов Yandex.Cloud"

2022-07-21 12:12 UTC, mrgreyves requested changes
Здравствуйте!)
У вас где то потерялись github workflow которые гоняют тесты
Может не смержили предыдущее дз?
Нужно добавить тесты

2022-07-21 13:09 UTC, Rezus2all commented
> Здравствуйте!) У вас где то потерялись github workflow которые гоняют тесты Может не смержили предыдущее дз? Нужно добавить тесты
Здравствуйте. Вы абсолютно правы. Добавил в ветку cloud-bastion директорию workflow. Просьба проверить.
Может не смержили предыдущее дз?  - предыдущее ДЗ в ветке play-travis?

2022-07-26 11:21 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все классно ^_^
ДЗ принимаю =)

2022-07-26 12:05 UTC, Rezus2all commented
> Здравствуйте!) Вот теперь все классно ^_^ ДЗ принимаю =)
.github/PULL_REQUEST_TEMPLATE.md - а вот этот конфликт, это разве нормльно?

2022-07-26 15:10 UTC, merged